import { useQuery } from "@tanstack/react-query";
import { fetcher } from "@/app/lib/fetcher";
import { IProperty } from "@/components/admin/properties/PropertiesList";

const dummyProperties: IProperty[] = [
  {
    _id: "1",
    title: "Luxury Apartment Downtown",
    description: "Spacious apartment with modern finishes",
    propertyType: "apartment",
    address: { city: "Lagos", state: "Lagos" },
    location: { type: "Point", coordinates: [3.3792, 6.5244] },
    bedrooms: 3,
    bathrooms: 2,
    toilets: 2,
    area: 1200,
    garages: 1,
    price: 250000,
    status: "for sale",
    featured: true,
    sold: false,
    yearBuilt: 2020,
    amenities: ["Pool", "Gym", "Parking", "Toilet"],
    images: [
      "https://th.bing.com/th/id/OIP.wIhmCJrj7W8LQAuRAIkgAwHaFL?w=243&h=180&c=7&r=0&o=7&pid=1.7&rm=3",
    ],
    videos: [],
    floorPlans: [],
    additionalDetails: "Spacious with sea view",
    createdBy: "adminId",
  },
  {
    _id: "2",
    title: "Cozy House in Lekki",
    description: "Perfect family home with garden",
    propertyType: "house",
    address: { city: "Lekki", state: "Lagos" },
    location: { type: "Point", coordinates: [3.622, 6.443] },
    bedrooms: 4,
    bathrooms: 3,
    toilets: 3,
    area: 2000,
    garages: 2,
    price: 450000,
    status: "for sale",
    featured: false,
    sold: false,
    yearBuilt: 2018,
    amenities: ["Garden", "Security", "Garage"],
    images: [
      "https://th.bing.com/th/id/OIP.42Dw6eGPuVBE7MNW4R9V4QHaEx?w=265&h=180&c=7&r=0&o=7&pid=1.7&rm=3",
    ],
    videos: [],
    floorPlans: [],
    additionalDetails: "Family-friendly, near schools",
    createdBy: "adminId",
  },
  {
    _id: "3",
    title: "Office Space Marina",
    description: "Commercial office for lease",
    propertyType: "office",
    address: { city: "Marina", state: "Lagos" },
    location: { type: "Point", coordinates: [3.4, 6.45] },
    bedrooms: 0,
    bathrooms: 2,
    toilets: 2,
    area: 1500,
    garages: 0,
    price: 120000,
    status: "for rent",
    featured: false,
    sold: false,
    yearBuilt: 2015,
    amenities: ["Parking", "CCTV", "Elevator"],
    images: [
      "https://th.bing.com/th/id/OIP.RsaKTkQhCMDyR4HjcJNMhgHaEO?w=277&h=180&c=7&r=0&o=7&pid=1.7&rm=3",
    ],
    videos: [],
    floorPlans: [],
    additionalDetails: "Good for startups",
    createdBy: "adminId",
  },
  {
    _id: "4",
    title: "Modern Shop in Ikeja",
    description: "Retail space in high traffic area",
    propertyType: "shop",
    address: { city: "Ikeja", state: "Lagos" },
    location: { type: "Point", coordinates: [3.361, 6.605] },
    bedrooms: 0,
    bathrooms: 1,
    toilets: 1,
    area: 800,
    garages: 0,
    price: 80000,
    status: "for rent",
    featured: false,
    sold: false,
    yearBuilt: 2010,
    amenities: ["Parking", "Security Camera"],
    images: [
      "https://th.bing.com/th/id/OIP.l4nG7UfaHK1R-C3bzHJ2QgHaE8?w=276&h=180&c=7&r=0&o=7&pid=1.7&rm=3",
    ],
    videos: [],
    floorPlans: [],
    additionalDetails: "High foot traffic location",
    createdBy: "adminId",
  },
  {
    _id: "5",
    title: "Beachfront Apartment Victoria Island",
    description: "Sea view apartment with balcony",
    propertyType: "apartment",
    address: { city: "Victoria Island", state: "Lagos" },
    location: { type: "Point", coordinates: [3.421, 6.428] },
    bedrooms: 2,
    bathrooms: 2,
    toilets: 2,
    area: 900,
    garages: 1,
    price: 300000,
    status: "for sale",
    featured: true,
    sold: false,
    yearBuilt: 2021,
    amenities: ["Pool", "Gym", "Balcony", "Security", "Toilet"],
    images: [
      "https://th.bing.com/th/id/OIP.qJ6a7U5GGRFvU95V9MB8ZwHaEK?w=272&h=180&c=7&r=0&o=7&pid=1.7&rm=3",
    ],
    videos: [],
    floorPlans: [],
    additionalDetails: "Luxury sea-facing apartment",
    createdBy: "adminId",
  },
  {
    _id: "6",
    title: "Suburban House Ikeja",
    description: "Quiet neighborhood, large garden",
    propertyType: "house",
    address: { city: "Ikeja", state: "Lagos" },
    location: { type: "Point", coordinates: [3.358, 6.605] },
    bedrooms: 5,
    bathrooms: 4,
    toilets: 4,
    area: 2500,
    garages: 2,
    price: 500000,
    status: "for sale",
    featured: false,
    sold: false,
    yearBuilt: 2016,
    amenities: ["Garage", "Garden", "Pool", "Security", "Toilet"],
    images: [
      "https://th.bing.com/th/id/OIP.Hg6-4apfO4uOX_j0VnbZ7AHaEK?w=282&h=180&c=7&r=0&o=7&pid=1.7&rm=3",
    ],
    videos: [],
    floorPlans: [],
    additionalDetails: "Ideal for families",
    createdBy: "adminId",
  },
  {
    _id: "7",
    title: "Downtown Office Lagos",
    description: "Modern office with open floor plan",
    propertyType: "office",
    address: { city: "Lagos", state: "Lagos" },
    location: { type: "Point", coordinates: [3.384, 6.524] },
    bedrooms: 0,
    bathrooms: 3,
    toilets: 3,
    area: 1800,
    garages: 2,
    price: 150000,
    status: "for rent",
    featured: false,
    sold: false,
    yearBuilt: 2019,
    amenities: ["Elevator", "CCTV", "Parking", "Conference Room"],
    images: [
      "https://th.bing.com/th/id/OIP.BfH9cWj3sJH2dX9Q4fR0iAHaEK?w=288&h=180&c=7&r=0&o=7&pid=1.7&rm=3",
    ],
    videos: [],
    floorPlans: [],
    additionalDetails: "Open space office with modern facilities",
    createdBy: "adminId",
  },
  {
    _id: "8",
    title: "Retail Shop Lekki Phase 1",
    description: "Shop in busy commercial complex",
    propertyType: "shop",
    address: { city: "Lekki", state: "Lagos" },
    location: { type: "Point", coordinates: [3.616, 6.444] },
    bedrooms: 0,
    bathrooms: 1,
    toilets: 1,
    area: 600,
    garages: 0,
    price: 70000,
    status: "for sale",
    featured: false,
    sold: false,
    yearBuilt: 2012,
    amenities: ["Parking", "Security Camera"],
    images: [
      "https://th.bing.com/th/id/OIP.DkLcYzYIqcd48y-xLjZpTAHaE7?w=270&h=180&c=7&r=0&o=7&pid=1.7&rm=3",
    ],
    videos: [],
    floorPlans: [],
    additionalDetails: "Prime location near mall",
    createdBy: "adminId",
  },
  {
    _id: "9",
    title: "Penthouse Victoria Island",
    description: "Top floor luxury penthouse",
    propertyType: "apartment",
    address: { city: "Victoria Island", state: "Lagos" },
    location: { type: "Point", coordinates: [3.423, 6.429] },
    bedrooms: 4,
    bathrooms: 3,
    toilets: 3,
    area: 2000,
    garages: 2,
    price: 750000,
    status: "for sale",
    featured: true,
    sold: false,
    yearBuilt: 2022,
    amenities: ["Pool", "Gym", "Terrace", "Security", "Garage"],
    images: [
      "https://th.bing.com/th/id/OIP.BuJg7S-Y5M0N27e-DqopCgHaEK?w=282&h=180&c=7&r=0&o=7&pid=1.7&rm=3",
    ],
    videos: [],
    floorPlans: [],
    additionalDetails: "Exclusive penthouse with terrace",
    createdBy: "adminId",
  },
  {
    _id: "10",
    title: "Small Office Ikeja",
    description: "Compact office space for startups",
    propertyType: "office",
    address: { city: "Ikeja", state: "Lagos" },
    location: { type: "Point", coordinates: [3.359, 6.604] },
    bedrooms: 0,
    bathrooms: 1,
    toilets: 1,
    area: 700,
    garages: 1,
    price: 50000,
    status: "for rent",
    featured: false,
    sold: false,
    yearBuilt: 2018,
    amenities: ["CCTV", "Parking", "Elevator"],
    images: [
      "https://th.bing.com/th/id/OIP.Mqoqsaz42l1GdK3iVdmcZAHaEK?w=282&h=180&c=7&r=0&o=7&pid=1.7&rm=3",
    ],
    videos: [],
    floorPlans: [],
    additionalDetails: "Affordable office near transit",
    createdBy: "adminId",
  },
];

// -------------------- PROPERTIES --------------------
// export function useProperties() {
//   return useQuery({
//     queryKey: ["properties"],
//     queryFn: () => fetcher("/api/properties"),
//     staleTime: 5 * 60 * 1000, // 5 minutes
//   });
// }
export function useProperties() {
  return {
    data: dummyProperties,
    isLoading: false,
  };
}


// -------------------- TOURS --------------------
export function useTours() {
  return useQuery({
    queryKey: ["tours"],
    queryFn: () => fetcher("/api/tours"),
    staleTime: 5 * 60 * 1000,
  });
}

// -------------------- INQUIRIES --------------------
export function useInquiries() {
  return useQuery({
    queryKey: ["inquiries"],
    queryFn: () => fetcher("/api/inquiries"),
    staleTime: 5 * 60 * 1000,
  });
}

// -------------------- URGENT ITEMS --------------------
export function useUrgentItems() {
  return useQuery({
    queryKey: ["urgent-items"],
    queryFn: () => fetcher("/api/tours?urgent=true"),
    staleTime: 2 * 60 * 1000,
  });
}